### ISSUE TITLE
Stopping playback isn't possible

### ISSUE THREAD

**Issue by ohadbenita** [Fenton-Fenton-Fenton/alexa-tube#3]
Hi,

Given I've started playing a long video and I want to stop it, it's not possible
Commands like "Ask youtube to stop playing" get a response of "Currently playing VIDEO_NAME" until the video finishes

Any chance this can be fixed ?

Thanks,
Ohad

**Comment by Fenton-Fenton-Fenton** [comment]
The issue is that you are using the skill name in your Stop request - just ask Alexa to Stop/Pause without saying YouTube and it should work fine

**Comment by ohadbenita** [comment]
@Fenton-Fenton-Fenton I did and it didn't work.
The root cause of the isssue is testing through the Alexa Voice simulator in the Alexa skill configuration page - the skill just kept saying it's playing the same video from the test I've made in this page

Once I've disabled and re-enabled the skill all was behaving normally
So I leave it to you whether the issue can be closed or should be fixed

Thanks

**Comment by Fenton-Fenton-Fenton** [comment]
Audio playback isn't supported in the Voice Simulator - this is why you were getting strange results as there are additional calls to the lambda function which are triggered by audio playback on a real device.

**Comment by ohadbenita** [comment]
ok then - I believe it's worth mentioning that whenever voice simulator is used the skill needs to be disabled and re-enabled to work correctly

**Comment by Fenton-Fenton-Fenton** [comment]
You shouldn't need to re-enable the skill - used the simulator during development without doing that. Just making a new search on a real device will reset the config. I'll update the readme to say not to use the simulator to avoid confusion

**Comment by Fenton-Fenton-Fenton** [comment]
I've also addressed the issue of using "Ask youtube to STOP" rather than just "STOP".

Thanks for flagging this up
