### ISSUE TITLE
"NOTE doing so is against the youtube terms of service"

### ISSUE THREAD

**Issue by Gelezako** [Fenton-Fenton-Fenton/alexa-tube#4]
Where is I can found more information about this problem?
Can the developer google administration block my account?
Thanks

**Comment by Fenton-Fenton-Fenton** [comment]
https://developers.google.com/youtube/terms/api-services-terms-of-service

As the skill runs within your own private, personal AWS instance, there isn't really anyway that google can tell what you are doing with the API data. There haven't been any reports of people getting blocked for using ytdl which this skill utilises.

**Comment by Gelezako** [comment]
cool, thanks
