### ISSUE TITLE
dropbox error

### ISSUE THREAD

**Issue by The-Clockmaker** [Fenton-Fenton-Fenton/alexa-tube#5]
I get "there was an error loading settings from dropbox"
Any idea where I mightve gone wrong?

Or sometimes "There was a problem with the requested skill's response"

**Comment by Fenton-Fenton-Fenton** [comment]
The most likely issue is that you haven't copied the dropbox token properly. Make sure it doesn't have any extra spaces at the beginning or the end

**Comment by tartanguru** [comment]
Closing as no feedback from OP
