### ISSUE TITLE
Alexa refuses.

### ISSUE THREAD

**Issue by vasilivna** [Fenton-Fenton-Fenton/alexa-tube#9]
"I couldn't find any enabled video skills. Go to the Music, Video, & Books section of your Alexa app to set up blah blah blah", she tells me.

I tried changing the invocation name from youtube to something else as well and it didn't help.

**Comment by Fenton-Fenton-Fenton** [comment]
It sounds like you haven't enabled the skill properly. Check the following:-

Make sure you have the Alexa trigger setup for the lambda function.
Make sure you have set up the skill in the same language as your device is set to
Make sure your device isn't login in as another user

**Comment by Fenton-Fenton-Fenton** [comment]
Closing as no response
